
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  name = "github.com/BurntSushi/toml"
  revision = "v0.3.1"

[[constraint]]
  name = "github.com/bitly/go-hostpool"
  revision = "a3a6125de932"

[[constraint]]
  name = "github.com/bitly/timer_metrics"
  revision = "b1c65ca7ae62"

[[constraint]]
  name = "github.com/blang/semver"
  revision = "v3.5.1"

[[constraint]]
  name = "github.com/bmizerany/perks"
  revision = "d9a9656a3a4b"

[[constraint]]
  name = "github.com/golang/snappy"
  revision = "2e65f85255db"

[[constraint]]
  name = "github.com/judwhite/go-svc"
  revision = "v1.0.0"

[[constraint]]
  name = "github.com/julienschmidt/httprouter"
  revision = "v1.2.0"

[[constraint]]
  name = "github.com/mreiferson/go-options"
  revision = "0c63f026bcd6"

[[constraint]]
  name = "github.com/nsqio/go-diskqueue"
  revision = "74cfbc9de839"

[[constraint]]
  name = "github.com/nsqio/go-nsq"
  revision = "v1.0.7"
